theme:
  logo: icon.png
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: black
      toggle:
        icon: material/weather-night


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

site_name: BeauPy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences